### ISSUE TITLE
functional and non-functional

### ISSUE THREAD

**Issue by giokats** [anagno/CinemaIs#2]
Functional
1) Για να μπορέσει κάποιος να ησέλθει στο σύστημα θα πρέπει να κάνει login αλλιώς register.
2) Μόλις ο πελάτης βρει την ταινία, την ημέρα και την ώρα που θέλει μεταβαίνει στον εικονικό χώρο της αίθουσας για να επιλέξει θέση.Αν δεν βρει γυρίζει πίσω και επιλέγει άλλη μέρα ή ταινία. Αν βρει θέσεις προσωράει στην πληρωμή των εισητηρίων.
3)Το σύστημα θα παρέχει πληροφορές για τις ταινίες καθώς και για τους ηθοποιούς. Το τμήμα marketing θα παρέχει το υλικό αυτό και θα είναι υπεύθυνο για την συντήρησή του.
4) Το σύστημα μετά την πληρωμή των εισητηρίων θα κατοχυρώνει τις θέσεις, ενημερώνοντας την αντίστοιχη βάση δεδομένων.
5) Παράλληλα θα ενημέρωνει την βάση δεδομένων των administrator για τις κρατημένες θέσεις της συγκεκριμένης ταινίας και αίθουσας  καθώς και για τις συνολικές εισπράξεις.

Non-Functional
1)Το σύστημα θα αντλεί πληροφορίες από την κύρια βάση δεδομένων για τις ταινίες τις μέρες, τις ώρες και τις αίθουσες που θα παίζονται.
2) Για ασφάλεια οι πληροφορίες για τους εγγεγραμμένους χρήστες θα βρίσκονται σε ξεχωριστή βάση δεδομένων, ενώ πληροφορίες για την πιστωτική κάρτα που θα πληρώνουν δεν θα αποθυκεύονται καν.
3) Για λόγους ασφαλείας για να μπορέσει κάποιος να κάνει κράτηση εισητηρίων θα πρέπει να είναι εγγεγραμμένος στην αντίστοιχη βάση.

**Comment by anagno** [comment]
Δεν εβγαλες ακρη με το notepad++ ;;;

**Comment by giokats** [comment]
Όχι δυστυχώς.....θα το βρω όμως
Στις 16 Ιαν 2015 1:50 ΜΜ, ο χρήστης "Vasilis-Thanos Anagnostopoulos" <
notifications@github.com> έγραψε:
