### ISSUE TITLE
Ανέβασε το αρχικό αρχείο των κλάσεων

### ISSUE THREAD

**Issue by anagno** [anagno/CinemaIs#3]
Ανέβασε το αρχικό αρχείο των κλάσεων. Και κοίτα τί ανεβάζω και εγώ !!! Το sequence το είχα κάνει ...

**Comment by anagno** [comment]
Άσε τώρα είδα ότι τα είχα ανεβάσει ...

**Comment by giokats** [comment]
εντάξει εγώ το έγραψα και στα Αγγλικά!

Στις 24 Ιανουαρίου 2015 - 10:27 π.μ., ο χρήστης Vasilis-Thanos
Anagnostopoulos notifications@github.com έγραψε:
