### ISSUE TITLE
Λειτουργικές απαιτήσεις

### ISSUE THREAD

**Issue by giokats** [anagno/CinemaIs#5]
Να βάλουμε σαν λειτουργική απαίτηση, εφόσον έχουμε βάλει ότι θα κρατάει ιστορικό πελάτη και ότι θα πρεοτείνει ταινίας ανάλογα με το ιστορικό του πελάτη.
Επίσης θα μπορούσε να μπει, να μπορεί ο χρήστης με ένα μικρό ποσό να κατεβάσει ή να δει την ταινία στον υπολογιστή του.

**Comment by anagno** [comment]
Για τον 2ο κομμάτι το κάνουμε πολύ πολύπλοκο ... Θα πρέπει να αλλάξουμε και άλλα πράγματα... Το 1ο είανι πολύ καλό ...
