### ISSUE TITLE
Σκοπός και στόχος του Π.Σ.

### ISSUE THREAD

**Issue by giokats** [anagno/CinemaIs#7]
Το Π.Σ. αναμένεται να αποφέρει οφέλη και στον τομέα της εύρεσης περισσότερων χορηγών

**Comment by anagno** [comment]
τί χορηγούς ;;;για ποιο πράγμα ;;;

**Comment by giokats** [comment]
για τον κινηματογράφο και καλά...τις διαφημήσεις που δείχνει πριν ξεκινήσει η ταινία.

**Comment by anagno** [comment]
Τοτε δεν αρκει αυτο που ηδη γραψαμε στους σκοπους ;;;
