### ISSUE TITLE
Συμπλήρωση μπλα μπλα για τα διαγράμματα των κλάσεων

### ISSUE THREAD

**Issue by anagno** [anagno/CinemaIs#8]
Αν μπορείς γράψε το μπλα μπλα για το διάγραμα των κλάσεων και το διάγραμμα κατάστασης διότι δεν είμαι σίγουρος τί θες να πεις με αυτά ...

**Comment by anagno** [comment]
Και αν γίνετε κάνε το μέχρι αύριο για να τον ρωτήσουμε επίτοπου τί λείπει ...

**Comment by anagno** [comment]
@giokats  Να σε πω... Ανέβασε ότι είναι να ανεβάσεις για να τελειώνουμε με αυτό ...

**Comment by giokats** [comment]
ναι έχεις δίκιο. Θα τα έχω όλα έτοιμα μέχρι την πέμπτη. Θα το έκανα από
τώρα αλλά σήμερα και αύριο έχω να κάνω ένα project που μου στείλανε για μια
δουλειά.

Στις 10 Φεβρουαρίου 2015 - 8:09 μ.μ., ο χρήστης Vasilis-Thanos
Anagnostopoulos notifications@github.com έγραψε:

**Comment by giokats** [comment]
Τα ανεβασα και τα τελικά. Δες και πες μου...

Στις 10 Φεβρουαρίου 2015 - 9:01 μ.μ., ο χρήστης Gio Ka <
giorgikatsis@gmail.com> έγραψε:

**Comment by anagno** [comment]
1)Τί σχέση έχει ο πίανακας που πρόσθεσες με τους συμβολισμούς που χρησιμοποιούμε στο διάγραμμα ;;; Έχεις βάλει πράγματα που ούτε καν έχουμε στο σχήμα μας και έχεις παραλείψει άλλα πράγματα τα οποία τα έχουμε !!!!

2)"Στο παρακάτω διάγραμμα κλάσεων (Σχήμα 3.6) περιγράφεται η διαδικασία
επιλογής της ταινίας που επιθυμεί ο πελάτης να δει καθώς και την/τις θέση/εις που θέλει
να κρατήσει" -> Πως στο καλό φαίνετε αυτό ;;; Υποτίθεται ότι πρέπει να περιγραφτούν οι κλάσεις ... Να πούμε π.χ. ότι οι κλάση ticket είναι για την αναπαράσταση των ειστητηρίων στο πρόγραμμα μας και περιλαμβάνει αυτές τις μεταβλητές και έχεις αυτές τις συναρτήσεις οι οποίες κάνουν μπλα μπλα 

3)Διάγραμμα καταστάσεων το οποίο ζήτησε

4) Γράφετα σε txt αρχείο ... Το docx έχει θέματα και δεν μπορώ να εξάγω τις εικόνες που αποθηκεύεις εκεί μέσα... Εξ ού και ο ξεχωριστός φάκελος με όλες τις εικόνες ...

**Comment by giokats** [comment]
Τελικά να κάτσω να γράψω για την κάθε μία κλάση ξεχωριστά; δεν είχε πει ότι
δεν είναι απαραίτητο; θα βγει πολύ μεγάλο

Στις 12 Φεβρουαρίου 2015 - 2:06 μ.μ., ο χρήστης Vasilis-Thanos
Anagnostopoulos notifications@github.com έγραψε:

**Comment by anagno** [comment]
Για μένα καλό θα ήταν για να είναι πλήρες ...

**Comment by giokats** [comment]
εντάξει με το διάγραμμα κλάσεων. Τα έβαλα σε ένα txt αρχείο. Βάλ τα πάνω
από το διάγραμμα.

2015-02-12 17:00 GMT+02:00 Vasilis-Thanos Anagnostopoulos <
notifications@github.com>:

**Comment by giokats** [comment]
Όσο αφορά το διάγραμμα καταστάσεων το αφήνω λίγο για να τελειώσω με τα
δίκτυα.  Άλλα έτσι κι αλλιώς έχουμε κάνει ήδη 4....

Στις 12 Φεβρουαρίου 2015 - 8:14 μ.μ., ο χρήστης Gio Ka <
giorgikatsis@gmail.com> έγραψε:

**Comment by anagno** [comment]
1)Δεν βλέπω να ανέβασες τπτ ... Κοίτα έτσι και άλλιώς αυτά που ανέβασα να δεις αν μου ξέφυγε τπτ ...
2)Έχουμε ήδη 4 αλλά τα ζήτησε ... Βάλτου τα να μην έχουμε παρατράγουδα ...

**Comment by giokats** [comment]
πάρε με πάλι αν μπορείς γτ μου τελείωσε η κάρτα

Στις 13 Φεβρουαρίου 2015 - 12:53 μ.μ., ο χρήστης Vasilis-Thanos
Anagnostopoulos notifications@github.com έγραψε:

**Comment by giokats** [comment]
Εντάξει και το διάγραμμα καταστάσεων....το έχω ανεβάσει

Στις 13 Φεβρουαρίου 2015 - 2:43 μ.μ., ο χρήστης Gio Ka <
giorgikatsis@gmail.com> έγραψε:

**Comment by anagno** [comment]
Το ενσωμάτωσα και στο pdf ... Νομίζω τελειώσαμε με αυτή την μλκ ...
